name: Deploy to EC2  # Optional: You can add a name for the workflow

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Create directory on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "mkdir -p /home/ec2-user/tick-tack-app/front-end"

      - name: List files for debugging
        run: |
          pwd
          ls -al

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r * ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/tick-tack-app/front-end
